2021-06-08 17:28:09,477 - __main__ - INFO - Error detected
Traceback (most recent call last):
  File "C:\Work\Работа\Питон\COVID_19_ 9880\Cоздание_исследований\create_Antitel.py", line 31, in genlog
    self.create_antitel()
  File "C:\Work\Работа\Питон\COVID_19_ 9880\Cоздание_исследований\create_Antitel.py", line 243, in create_antitel
    driver.find_element_by_css_selector("#itemForm\:covid-researches-doAction-РћС‚РїСЂР°РІР»РµРЅРІР»Р°Р±РѕСЂР°С‚РѕСЂРёСЋ1")
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#itemForm\:covid-researches-doAction-\u041e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0432\u043b\u0430\u0431\u043e\u0440\u0430\u0442\u043e\u0440\u0438\u044e1"}
  (Session info: chrome=90.0.4430.212)

