2021-05-14 12:26:46,617 - __main__ - INFO - Error detected
Traceback (most recent call last):
  File "C:\Work\Работа\Питон\COVID_19_ 9880\Cоздание_исследований\create_PCR.py", line 29, in genlog
    self.create_pcr()
  File "C:\Work\Работа\Питон\COVID_19_ 9880\Cоздание_исследований\create_PCR.py", line 48, in create_pcr
    driver.find_element_by_css_selector("#j_idt60 > div.nano.layout-tabmenu-nav.has-scrollbar > ul > li:nth-child(9) > a").click()
AttributeError: 'NoneType' object has no attribute 'click'
