2021-06-23 15:37:01,002 - create_Antitel - ERROR - Error detected
Traceback (most recent call last):
  File "C:\Users\Webdom16\Desktop\Питон\COVID_19_ 9880\Cоздание_исследований\create_Antitel.py", line 31, in genlog
    self.create_antitel()
  File "C:\Users\Webdom16\Desktop\Питон\COVID_19_ 9880\Cоздание_исследований\create_Antitel.py", line 43, in create_antitel
    driver.find_element_by_id("form:usernameInput").click()
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=91.0.4472.114)

